# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|  

  # make vm node1 - master
  config.vm.define "node1" do |node|
    node.vm.box = "generic/centos7"
    node.vm.provider "virtualbox" do |vb|
      vb.cpus = 4  
      vb.memory = "8129"      
    end       
    node.vm.box_check_update = false
    node.vm.hostname = "master-test-01"
    node.vm.network "public_network", ip: "172.20.10.101"
    node.vm.provision "shell", path: "01.setup-master-node.sh"   
  end
end
