apiVersion: getambassador.io/v2
kind: Module
metadata:
  name:  ambassador
spec:
  config:
    resolver: endpoint
    load_balancer:
      policy: round_robin
    x_forwarded_proto_redirect: true
    use_remote_address: false

